config/routes.rb
Rails.application.routes.draw do
  resources :reviews
  resources :pictures
  resources :users, only: [:new, :create]
  resources :restaurants
  resources :comments

  root 'restaurants#index'
  get  '/help',    to: 'static_pages#help'
  get  '/about',   to: 'static_pages#about'
  get  '/contact', to: 'static_pages#contact'
  get  '/signup',  to: 'users#new'

  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  post '/logout',  to: 'sessions#destroy'

  resources :users

  # get 'restaurants/index'


  # root 'restaurants#index'

end

app/models/picture.rb
class Picture < ApplicationRecord
  has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"

  validates_attachment_content_type :image, :content_type => /\Aimage\/.*/
  validates :image, presence: true

  # belongs_to :user
  belongs_to :restaurant

end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  before_action :set_picture, only: [:show, :edit, :update, :destroy]
  before_action :authorize
  # GET /pictures
  # GET /pictures.json
  def index
    @pictures = Picture.all
  end

  # GET /pictures/1
  # GET /pictures/1.json
  def show
  end

  # GET /pictures/new
  def new
    @picture = Picture.new
  end

  # GET /pictures/1/edit
  def edit
  end

  # POST /pictures
  # POST /pictures.json
  def create
    @picture = Picture.new(picture_params)

    respond_to do |format|
      if @picture.save
        format.html { redirect_to @picture.restaurant, notice: 'Picture was successfully created 🤠' }
        format.json { render :show, status: :created, location: @picture }
      else
        format.html { redirect_to @picture.restaurant }
        format.json { render json: @picture.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pictures/1
  # PATCH/PUT /pictures/1.json
  def update
    respond_to do |format|
      if @picture.update(picture_params)
        format.html { redirect_to @picture, notice: 'Picture was successfully updated y.' }
        format.json { render :show, status: :ok, location: @picture }
      else
        format.html { render :edit }
        format.json { render json: @picture.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pictures/1
  # DELETE /pictures/1.json
  def destroy
    @picture.destroy
    respond_to do |format|
      format.html { redirect_to pictures_url, notice: 'Picture was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_picture
      @picture = Picture.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def picture_params
      params.require(:picture).permit(:image, :restaurant_id)
    end
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/views/pictures/_form.html.erb
<%= form_with(model: @picture, local: true, html: { multipart: true }) do |form| %>

  <div class="field">
    <%= form.hidden_field :restaurant_id, id: :restaurant_id, value: !@picture.new_record? ? @picture.restaurant.id : @restaurant.id %>
  </div>


  <div class="field">
    <%= form.label :image %>
    <%= form.file_field :image, id: :picture_image %>
  </div>

  <div class="actions">
    <%= form.submit class: "btn btn-primary" %>
  </div>

<% end %>

app/views/pictures/edit.html.erb
<h1>Editing Picture</h1>

<%= render 'form', picture: @picture %>

<%= link_to 'Show', @picture %> |
<%= link_to 'Back', pictures_path %>

app/views/pictures/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Pictures</h1>

<% @pictures.each do |picture| %>
<div class="col-md-4">
  <div class="panel panel-primary">
    <%= picture.title %>
    <%= image_tag(picture.image, class: 'img-responsive img-thumbnail', style: 'max-height: 300px;') %>
    <%= link_to 'Show', picture %>
    <%= link_to 'Edit', edit_picture_path(picture) %>
    <%= link_to 'Destroy', picture, method: :delete, data: { confirm: 'Are you sure?' } %>
  </div>
</div>
<% end %>
<br>

<%= link_to 'New Picture', new_picture_path %>

app/views/pictures/new.html.erb
<h1>New Picture</h1>

<%= render 'form', picture: @picture %>

<%= link_to 'Back', pictures_path %>

app/views/pictures/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @picture.title %>
</p>

<p>
  <strong>Image:</strong>
  <%= link_to image_tag(@picture.image.url(:medium)), @picture.image.url %>
  <!-- <img src="<%#= @picture.image.url(:medium) %>" alt=""> -->
</p>

<%= link_to 'Edit', edit_picture_path(@picture) %> |
<%= link_to 'Home', root_path %>