config/routes.rb
Rails.application.routes.draw do
  resources :reviews
  resources :pictures
  resources :users, only: [:new, :create]
  resources :restaurants
  resources :comments

  root 'restaurants#index'
  get  '/help',    to: 'static_pages#help'
  get  '/about',   to: 'static_pages#about'
  get  '/contact', to: 'static_pages#contact'
  get  '/signup',  to: 'users#new'

  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  post '/logout',  to: 'sessions#destroy'

  resources :users

  # get 'restaurants/index'


  # root 'restaurants#index'

end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  belongs_to :user
  has_many :pictures
  has_many :reviews
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :find_restaurant, only: [:show, :edit, :update, :destroy]
  before_action :authorize

  # GET /restaurants
  # GET /restaurants.json
  def index
    @restaurants = Restaurant.all
  end

  # GET /restaurants/1
  # GET /restaurants/1.json
  def show
    @picture = Picture.new
  end

  # GET /restaurants/new
  def new
    @restaurant = Restaurant.new
    @picture = Picture.new
  end

  # GET /restaurants/1/edit
  def edit
  end

  # POST /restaurants
  # POST /restaurants.json
  def create
    @restaurant = Restaurant.new(restaurant_params)
    @picture = Picture.new

    respond_to do |format|
      if @restaurant.save
        format.html { redirect_to @restaurant, notice: 'Restaurant was successfully created 🤠 ' }
        format.json { render :show, status: :created, location: @restaurant }
      else
        format.html { render :new }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /restaurants/1
  # PATCH/PUT /restaurants/1.json
  def update
    respond_to do |format|
      if @restaurant.update(restaurant_params)
        format.html { redirect_to @restaurant, notice: 'Restaurant was successfully updated.' }
        format.json { render :show, status: :ok, location: @restaurant }
      else
        format.html { render :edit }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /restaurants/1
  # DELETE /restaurants/1.json
  def destroy
    @restaurant.destroy
    respond_to do |format|
      format.html { redirect_to restaurants_url, notice: 'Restaurant was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def restaurant_params
      params.require(:restaurant).permit(:name, :comment, :price, :user_id, :url)
    end

    def find_restaurant
      @restaurant = Restaurant.find(params[:id])
    end
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/restaurants/_form.html.erb
<div class="col-md-4 col-md-offset-4">

<%= form_with(model: restaurant, local: true) do |form| %>
  <% if restaurant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(restaurant.errors.count, "error") %> prohibited this restaurant from being saved:</h2>

      <ul>
      <% restaurant.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>g
    </div>
  <% end %>

  <%= form.hidden_field :user_id, id: :user_id, value: @current_user.id %>

  <div class="form-group">
    <%= form.label :name, "Restaurant Name", class: "new-restaurant" %>
    <%= form.text_field :name, id: :restaurant_name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :comment, "Rating", class: "new-restaurant" %>
    <%= form.select :comment, options_for_select(["🙌🏼","🤷🏼","💩"].each{|u| [u, u] }), {}, {class: "form-control"}  %>  </div>

  <div class="form-group">
    <%= form.label :price, "Price", class: "new-restaurant" %>
    <%= form.select :price, options_for_select(["💰","💰💰","💰💰💰"].each{|u| [u, u] }), {}, {class: "form-control"}  %>
  </div>

  <div class="form-group">
    <%= form.label :url, "Website", class: "new-restaurant" %>
    <%= form.text_field :url, id: :restaurant_name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.submit "Create Restaurant", class: "btn btn-success" %>
  </div>
<% end %>

</div>

app/views/restaurants/edit.html.erb
<h1>Editing Restaurant</h1>

<%= render 'form', restaurant: @restaurant %>

<%= link_to 'Show', @restaurant %> |
<%= link_to 'Back', restaurants_path %>

app/views/restaurants/index.html.erb
<p id="notice"><%= notice %></p>

<div class="table table-striped table-hover panel">
  <h2>About us</h2>
  <h3 class='fontype'>WynEats is a friendly webpage for the Wyncode community to view restaurants in the Wynwood area focused for onboarding Wyncoders from out of state and new to the area!</h3>
</div>
<br>
<div class="restaurant-pics">
  <% @restaurants.each_with_index do |restaurant, index| %>
    <div class="col-md-12  ">
      <figure>
        <figcaption>
          <div class="text-left">
            <h2><%= restaurant.name %></h2>
          </div>

        </figcaption>
        <div class="img-responsive text-center">
          <!-- <%#= image_tag restaurant.picture %>  something like this when paperclip implemented -->
          <%= image_tag restaurant.pictures.sample.image, class: "test_class" rescue nil %>
          <div class="section-2">
            <%= link_to 'Learn More', restaurant, class: "test_class" %>
          </div>
        </div>
      </figure>
    </div>
  <% end %>
</div>

app/views/restaurants/new.html.erb
<div class="restaurant-new-container">

  <div class="col-md-7 col-md-offset-4">
    <br>
    <br>
    <h1></h1>
    <br>
    <br>
    <br>
  </div>

</div>
<br>
    <%= render 'form', restaurant: @restaurant %>

    <!-- <%= link_to 'Back', restaurants_path %> -->

app/views/restaurants/show.html.erb
<p id="notice"><%= notice %></p>

<p>

  <% if @restaurant.url %>
  <%= link_to @restaurant.name, @restaurant.url, target: "_blank" %>
  <% else %>
  <%= @restaurant.name %>
  <% end %>
</p>
<p>
  <!-- <strong>Rating:</strong> -->
  <%= @restaurant.comment %>
</p>
</p>
<p>
  <!-- <strong>Price:</strong> -->
  <%= @restaurant.price %>
</p>


<div class="img-responsive text-center">
<div class='picbox'>
  <% @restaurant.pictures.each do |picture| %>
  <p id="image-pic" >
    <%= image_tag picture.image, class: "test_class" %>
    <br>
  </p>
  <% end %>
  <br>
  </div>
</div>

<h4>New Picture</h4>
<%= render 'pictures/form', picture: @picture %>

<% if @current_user == @restaurant.user %>
<td><%= link_to 'Edit', edit_restaurant_path(@restaurant) %></td>
<td><%= link_to 'Destroy', @restaurant, method: :delete, data: { confirm: 'Are you sure?' } %></td>
<% end %>
<%= link_to 'Back', restaurants_path %>