config/routes.rb
Rails.application.routes.draw do
  resources :reviews
  resources :pictures
  resources :users, only: [:new, :create]
  resources :restaurants
  resources :comments

  root 'restaurants#index'
  get  '/help',    to: 'static_pages#help'
  get  '/about',   to: 'static_pages#about'
  get  '/contact', to: 'static_pages#contact'
  get  '/signup',  to: 'users#new'

  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  post '/logout',  to: 'sessions#destroy'

  resources :users

  # get 'restaurants/index'


  # root 'restaurants#index'

end

app/views/layouts/_footer.html.erb
<html>
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Document</title>
</head>
<body>

</body>
</html>

app/views/layouts/_header.html.erb
<!-- <header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container text-xs-center">
    <%= link_to "WynEats", '#', id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home",   '#' %></li>
        <li><%= link_to "Help",   '#' %></li>
        <li><%= link_to "Log in", '#' %></li>
      </ul>
    </nav>
  </div>
</header> -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WynEats</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
      <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.0/jquery.min.js"></script>
      <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body class="<%=controller_name  %> <%= controller.action_name  %> ">

    <nav class="navbar navbar-default">

      <div class="container">
        <div class="header-container" id="bootstrap-overrides">
          <div class="navbar-header">
            <%= link_to "WynEats", root_path, class: "navbar-brand" %>
          </div>

          <ul class="nav navbar-nav navbar-right">
            <% if !current_user %>
            <li><%= link_to "Sign-Up", signup_path, class: "navbar-brand" %></li>
            <% end %>
            <% if current_user %>
              <li><%= link_to "Sign Out", logout_path, method: :destroy, class: "navbar-brand" %></li>
            <% else  %>
              <li><%= link_to "Log In", login_path, class: "navbar-brand" %></li>
              <% end %>

          </ul>

          <ul class="nav navbar-nav">

            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">munchies sneek peek<span class="caret"></span></a>
              <ul class="dropdown-menu" role="menu">
                <% Restaurant.all.each do |restaurant| %>
                  <li class="<%= 'active' if params[:restaurants] == restaurant.name %>">
                    <%= link_to restaurant.name, restaurant_path(restaurant), class: "link" %>
                  </li>
                <% end %>
              </ul>
            </li>

            <% if current_user %>
              <li><%= link_to "Add Restaurant", new_restaurant_path, class: "navbar-brand shadow" %></li>
            <% end %>
          </ul>

          </div>

        </div>
      </div>
    </nav>



    <div class="container" id= 'body'>

          <p class="alert"><%= alert %></p>
          <%= yield %>
    </div>



    <nav class="navbar navbar-default navbar-fixed-bottom">

      <div class="container">
        <div class="header-container" id="bootstrap-overrides">
          <div class="navbar-header">
            <%= link_to "WynEats", root_path, class: "navbar-brand" %>
          </div>

          <ul class="nav navbar-nav navbar-right">
            <% if !current_user %>
            <li><%= link_to "Sign-Up", signup_path, class: "navbar-brand" %></li>
            <% end %>
            <% if current_user %>
              <li><%= link_to "Sign Out", logout_path, method: :destroy, class: "navbar-brand" %></li>
            <% else  %>
              <li><%= link_to "Log In", login_path, class: "navbar-brand" %></li>
              <% end %>

          </ul>

          <!-- <ul class="nav navbar-nav">

            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">munchies sneek peek<span class="caret"></span></a>
              <ul class="dropdown-menu" role="menu">
                <% Restaurant.all.each do |restaurant| %>
                  <li class="<%= 'active' if params[:restaurants] == restaurant.name %>">
                    <%= link_to restaurant.name, restaurant_path(restaurant), class: "link" %>
                  </li>
                <% end %>
              </ul>
            </li>

            <% if current_user %>
              <li><%= link_to "Add Restaurant", new_restaurant_path, class: "navbar-brand" %></li>
            <% end %>
          </ul> -->

          </div>
        </div>
      </div>
    </nav>






  </body>
</html>